import BodyCopy from "../../BodyCopy"

export const DigitalNativePreview = () => {
    return (
        <>
            <BodyCopy><span className="float-left text-5xl font-digital-native-serif">D</span>evin winced as he prodded the gaping hole in his belly. He lay back, sides heaving, on the black and white checked elevator floor. It was covered in blood, both his and the attacker's. What's black and white and red all over? he thought. He tried to smile, but the pain turned his expression to a grimace. The lurch in his stomach didn't help, the millisecond of suspension announcing that the elevator descended to the basement where his patients slept.</BodyCopy>
            <BodyCopy>The elevator's friendly beep announced every floor it passed on its way down. Thirty-three, thirty-two, thirty-one. Around the twenty-eighth floor, a blackness crept into the corners of Devin's vision. He wondered how much longer he had. Didn't they warn you, he scolded himself, told you that you couldn't please everyone? But you thought you were talented enough to pull it off, didn't you?  Ha!</BodyCopy>
            <BodyCopy>His breathing was coming harder now. He stared up at the descending elevator numbers that glowed green in the display box over the doors. A howl sounded high above him in the elevator shaft, and Devin held his breath. They were still up there, waiting. Cheated of their quarry. What was he doing, returning to where his patients rested, unaware of the danger?</BodyCopy>
            <BodyCopy>When a cat is dying, it leaves its clowder and roams far away to give up its ghost. Cats don't want their dead bodies decomposing at home, luring dangerous predators to where the kittens live. That was the explanation Devin liked best. Some behaviorists thought dying cats were merely seeking peace and quiet, but Devin preferred to think that they were keeping their families safe. So why am I going back home?</BodyCopy>
            <BodyCopy>What would his attackers do to his patients? How could he protect them, wounded as he was? The blackness grew in his vision and his pain seemed strange and far away. Think! he told himself. You'll be dead as a doorstop soon! His eyebrows went up. That's it.</BodyCopy>
            <BodyCopy>The elevator dinged and the doors opened into the basement hallway. In front of him was his normal world. Beige walls, tan low- pile carpet, stock photos of beaches hung every 10 feet up and down the hall. Familiar. Surrounding him in the elevator was his new nightmare of blood, pain, and death.</BodyCopy>
            <BodyCopy>Move! He willed himself to crawl across the slippery, blood- covered floor. He collapsed with his torso on the tan carpet and his legs inside the elevator. Hope we've got a good stain remover. He smiled. Now the doors couldn't close, and the elevator couldn't return to the upper floors to bring down death. It was a satisfying last act, he decided.</BodyCopy>
            <BodyCopy>Then the elevator doors closed on him. They squeezed his sides briefly and Devin cried out. The pain was front and center again. The doors opened and waited another thirty seconds before closing on him again. Another cry escaped him. This was a terrible plan, he thought.</BodyCopy>
            <BodyCopy>His vision was almost completely dark now. He pictured his patients finding his body in the morning, elevator still chewing him once every thirty seconds. He shuddered. Then he heard footsteps coming toward him from around the corner. He tensed. Was it Hank?</BodyCopy>
        </>
    );
};